### ISSUE TITLE
Pod问题

### ISSUE THREAD

**Issue by ZJF-Coder** [tianya2416/GKiOSNovel#3]
pod install时，有些资源会报问题，如：UICollectionView-ARDynamicHeightLayoutCell和EARestrictedScrollView，作者那边是ok？（翻墙了也一样）

**Comment by tianya2416** [comment]
我这边没什么问题，pod 1.8.0.beta.2

**Comment by ZJF-Coder** [comment]
谢谢没什么问题了，就是pod很慢，需要耐心等挺久才行
